# Generated by Django 4.1.1 on 2023-02-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karyawan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='nama',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
