# Generated by Django 4.1.1 on 2023-02-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karyawan', '0003_karyawan_created_karyawan_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
